/* =====================================================================
 *  Civico23 — Palette definitions (shared between palette-test and font-test)
 * =================================================================== */

const ALL_PALETTES = {
  // ===== ACTIVE — dal Brand Brief =====
  active: [
    {
      name: "C'è Vita Che Scorre",
      vibe: 'evoluzione · fiume · crescita continua',
      dark: '#1a2f2a',
      light: '#f4f7f0',
      accent: '#d4824a',
      swatches: [
        { bg: '#1a2f2a', fg: '#f4f7f0', label: 'Fondale' },
        { bg: '#3d7a6a', fg: '#f4f7f0', label: 'Corrente' },
        { bg: '#d4824a', fg: '#f4f7f0', label: 'Argilla' },
        { bg: '#a8c4a0', fg: '#1a2f2a', label: 'Riva' },
        { bg: '#f4f7f0', fg: '#1a2f2a', label: 'Schiuma' },
      ],
      btn2: { bg: '#1a2f2a', fg: '#f4f7f0' },
      why: '"C\'è vita che scorre" — la frase-manifesto emersa dal questionario. Verde fiume che scorre, argilla delle rive padovane. Il pilastro EVOLUZIONE: i figli crescono, i genitori pure, la musica cambia. Una palette che invecchia bene.',
    },
    {
      name: 'Cinque Voci',
      vibe: 'coralità · armonizzazione · unità nella diversità',
      dark: '#262040',
      light: '#faf5f0',
      accent: '#e06850',
      swatches: [
        { bg: '#262040', fg: '#faf5f0', label: 'Basso' },
        { bg: '#4a6fa5', fg: '#faf5f0', label: 'Tenore' },
        { bg: '#e06850', fg: '#faf5f0', label: 'Voce' },
        { bg: '#e8b960', fg: '#262040', label: 'Armonia' },
        { bg: '#faf5f0', fg: '#262040', label: 'Silenzio' },
      ],
      badgeBg: '#e06850',
      btn2: { bg: '#262040', fg: '#faf5f0' },
      why: '"Cantiamo in 5, armonizzazioni curate" — il pilastro CORALITÀ. Ogni colore è una voce: il basso profondo, il tenore blu, la voce rossa, l\'armonia dorata. 5 colori distinti che funzionano solo insieme, come voi sul palco.',
    },
    {
      name: 'Leggerezza Seria',
      vibe: 'ironia · profondità · il sorriso che pensa',
      dark: '#2a2540',
      light: '#fff8f2',
      accent: '#ff8c42',
      swatches: [
        { bg: '#2a2540', fg: '#fff8f2', label: 'Profondo' },
        { bg: '#6c5b9e', fg: '#fff8f2', label: 'Pensiero' },
        { bg: '#ff8c42', fg: '#fff8f2', label: 'Sorriso' },
        { bg: '#ffd166', fg: '#2a2540', label: 'Risata' },
        { bg: '#fff8f2', fg: '#2a2540', label: 'Pagina' },
      ],
      badgeBg: '#6c5b9e',
      btn2: { bg: '#2a2540', fg: '#fff8f2' },
      why: '"Ridiamo di cose serie" — il pilastro LEGGEREZZA CON SOSTANZA. Il viola è la riflessione, l\'arancio è la risata che rompe la serietà, il giallo è l\'allegria contagiosa. Per una band che fa pensare facendo ridere.',
    },
    {
      name: 'Forty',
      vibe: 'midlife · consapevolezza · il bello dei 40',
      dark: '#2b2b3a',
      light: '#f8f4ee',
      accent: '#b8704a',
      swatches: [
        { bg: '#2b2b3a', fg: '#f8f4ee', label: 'Mezzanotte' },
        { bg: '#b8704a', fg: '#f8f4ee', label: 'Rame' },
        { bg: '#7a6e8a', fg: '#f8f4ee', label: 'Grigio lilla' },
        { bg: '#c4a87a', fg: '#2b2b3a', label: 'Whisky' },
        { bg: '#f8f4ee', fg: '#2b2b3a', label: 'Carta avorio' },
      ],
      btn2: { bg: '#2b2b3a', fg: '#f8f4ee' },
      why: '"Forty — on turning forty" + "i quarantenni che diventano 50". Colori che sanno di consapevolezza: il rame invecchia bene, il whisky è caldo, il grigio lilla porta quel tocco di malinconia leggera. Eleganza di chi sa chi è.',
    },
    {
      name: "Don't Worry",
      vibe: 'ottimismo · freschezza · canzone nuova',
      dark: '#1a3048',
      light: '#fefbf3',
      accent: '#50b87a',
      swatches: [
        { bg: '#1a3048', fg: '#fefbf3', label: 'Mare' },
        { bg: '#50b87a', fg: '#fefbf3', label: 'Speranza' },
        { bg: '#f5a54a', fg: '#1a3048', label: 'Sole' },
        { bg: '#78c4d4', fg: '#1a3048', label: 'Cielo' },
        { bg: '#fefbf3', fg: '#1a3048', label: 'Schiuma' },
      ],
      badgeBg: '#50b87a',
      btn2: { bg: '#1a3048', fg: '#fefbf3' },
      why: '"Don\'t Worry fatta per la prima volta a San Bellino" — il momento in cui la band ha sentito di essere sé stessa. Verde speranza, sole arancio, cielo aperto. Fresca e ottimista, per chi dice "il meglio deve ancora venire".',
    },
    {
      name: 'Elio Energy',
      vibe: 'follia · libertà espressiva · colore puro',
      dark: '#1a1a2a',
      light: '#fffdf5',
      accent: '#e84060',
      swatches: [
        { bg: '#1a1a2a', fg: '#fffdf5', label: 'Notte' },
        { bg: '#e84060', fg: '#fffdf5', label: 'Magenta' },
        { bg: '#ffc830', fg: '#1a1a2a', label: 'Flash' },
        { bg: '#30c4b0', fg: '#1a1a2a', label: 'Electric' },
        { bg: '#fffdf5', fg: '#1a1a2a', label: 'Luce' },
      ],
      badgeBg: '#e84060',
      btn2: { bg: '#ffc830', fg: '#1a1a2a' },
      why: '"Eliooooo!" + "video deliranti" + "follia, ironia totale, libertà espressiva". Magenta, flash giallo, electric teal — è la palette più coraggiosa. Per chi vuole portare la follia anche nel visual. Perfetta per i video, pericolosa per il teatro. Ma chi ha detto che non si può?',
    },
  ],

  // ===== HIDDEN — prime 10 originali + 4 spostate =====
  hidden: [
    {
      name: 'Sera in Piazza',
      vibe: 'caldo · familiare · concerto estivo',
      dark: '#2b2139', light: '#faf3e8', accent: '#e8985a',
      swatches: [
        { bg: '#2b2139', fg: '#faf3e8', label: 'Notte' },
        { bg: '#5c4b8a', fg: '#faf3e8', label: 'Viola' },
        { bg: '#e8985a', fg: '#2b2139', label: 'Tramonto' },
        { bg: '#f2c87d', fg: '#2b2139', label: 'Oro' },
        { bg: '#faf3e8', fg: '#2b2139', label: 'Crema' },
      ],
      btn2: { bg: '#2b2139', fg: '#faf3e8' },
      why: 'Richiama le sere d\'estate a suonare in piazza.',
    },
    {
      name: 'Mattino a Casa',
      vibe: 'fresco · leggero · quotidiano',
      dark: '#1e3a3a', light: '#f7f1e6', accent: '#e07b5a',
      swatches: [
        { bg: '#1e3a3a', fg: '#f7f1e6', label: 'Bosco' },
        { bg: '#5a9e8f', fg: '#1e3a3a', label: 'Salvia' },
        { bg: '#e07b5a', fg: '#f7f1e6', label: 'Terracotta' },
        { bg: '#f2d4a0', fg: '#1e3a3a', label: 'Grano' },
        { bg: '#f7f1e6', fg: '#1e3a3a', label: 'Lino' },
      ],
      btn2: { bg: '#1e3a3a', fg: '#f7f1e6' },
      why: 'Il verde salvia è fresco senza essere freddo, la terracotta è domestica.',
    },
    {
      name: 'Palco Acceso',
      vibe: 'energico · scanzonato · ironico',
      dark: '#1a1a2e', light: '#fffbf0', accent: '#ff6b4a',
      swatches: [
        { bg: '#1a1a2e', fg: '#fffbf0', label: 'Notte' },
        { bg: '#ff6b4a', fg: '#fffbf0', label: 'Corallo' },
        { bg: '#ffc857', fg: '#1a1a2e', label: 'Giallo' },
        { bg: '#4ecdc4', fg: '#1a1a2e', label: 'Menta' },
        { bg: '#fffbf0', fg: '#1a1a2e', label: 'Panna' },
      ],
      badgeBg: '#ff6b4a',
      btn2: { bg: '#ffc857', fg: '#1a1a2e' },
      why: 'Colori vivaci e pop, energia da palco.',
    },
    {
      name: 'Vinile Caldo',
      vibe: 'profondo · qualità · Nicolò Fabi vibes',
      dark: '#2c1f14', light: '#f5ebe0', accent: '#c17a4a',
      swatches: [
        { bg: '#2c1f14', fg: '#f5ebe0', label: 'Mogano' },
        { bg: '#c17a4a', fg: '#f5ebe0', label: 'Ambra' },
        { bg: '#8b6d5c', fg: '#f5ebe0', label: 'Cuoio' },
        { bg: '#dcc5a8', fg: '#2c1f14', label: 'Sabbia' },
        { bg: '#f5ebe0', fg: '#2c1f14', label: 'Cotone' },
      ],
      btn2: { bg: '#2c1f14', fg: '#f5ebe0' },
      why: 'Toni caldi e terrosi come il legno di una chitarra acustica.',
    },
    {
      name: 'Prato della Valle',
      vibe: 'colorato · Padova · Modern Family',
      dark: '#263547', light: '#fef9f0', accent: '#e8a44a',
      swatches: [
        { bg: '#263547', fg: '#fef9f0', label: 'Blu Notte' },
        { bg: '#5c8a72', fg: '#fef9f0', label: 'Prato' },
        { bg: '#e8a44a', fg: '#263547', label: 'Miele' },
        { bg: '#d4726a', fg: '#fef9f0', label: 'Mattone' },
        { bg: '#fef9f0', fg: '#263547', label: 'Calce' },
      ],
      btn2: { bg: '#5c8a72', fg: '#fef9f0' },
      why: 'Blu notte, verde prato, miele dorato, mattone veneto.',
    },
    {
      name: 'Squadra A',
      vibe: 'avventura · squadra · A-Team meets papà',
      dark: '#1b2838', light: '#f4f0e8', accent: '#d4583a',
      swatches: [
        { bg: '#1b2838', fg: '#f4f0e8', label: 'Acciaio' },
        { bg: '#d4583a', fg: '#f4f0e8', label: 'Rosso' },
        { bg: '#e8b44c', fg: '#1b2838', label: 'Dorato' },
        { bg: '#7a8f7e', fg: '#f4f0e8', label: 'Militare' },
        { bg: '#f4f0e8', fg: '#1b2838', label: 'Carta' },
      ],
      btn2: { bg: '#1b2838', fg: '#f4f0e8' },
      why: 'Colori decisi ma non aggressivi: acciaio, rosso, dorato.',
    },
    {
      name: 'Shrinking',
      vibe: 'terapeutico · moderno · sorriso gentile',
      dark: '#2d3748', light: '#faf8f5', accent: '#6b9e78',
      swatches: [
        { bg: '#2d3748', fg: '#faf8f5', label: 'Grafite' },
        { bg: '#6b9e78', fg: '#faf8f5', label: 'Speranza' },
        { bg: '#e8a87c', fg: '#2d3748', label: 'Pesca' },
        { bg: '#b8c9d4', fg: '#2d3748', label: 'Cielo' },
        { bg: '#faf8f5', fg: '#2d3748', label: 'Nuvola' },
      ],
      btn2: { bg: '#2d3748', fg: '#faf8f5' },
      why: 'Verde speranza per la crescita, pesca per il calore, cielo per la leggerezza.',
    },
    {
      name: 'Pinguini',
      vibe: 'genuino · pop italiano · generazione',
      dark: '#292140', light: '#fff7ed', accent: '#f59e42',
      swatches: [
        { bg: '#292140', fg: '#fff7ed', label: 'Indaco' },
        { bg: '#f59e42', fg: '#292140', label: 'Arancio' },
        { bg: '#e85d75', fg: '#fff7ed', label: 'Fucsia' },
        { bg: '#58c4dc', fg: '#292140', label: 'Azzurro' },
        { bg: '#fff7ed', fg: '#292140', label: 'Latte' },
      ],
      badgeBg: '#f59e42',
      btn2: { bg: '#e85d75', fg: '#fff7ed' },
      why: 'Colori pop, freschi, da festival estivo.',
    },
    {
      name: 'Camicia e Chitarra',
      vibe: 'smart casual · papà lavoratore · eleganza ironica',
      dark: '#1a2332', light: '#f5f2ed', accent: '#c4873b',
      swatches: [
        { bg: '#1a2332', fg: '#f5f2ed', label: 'Navy' },
        { bg: '#c4873b', fg: '#f5f2ed', label: 'Cammello' },
        { bg: '#8b4d5c', fg: '#f5f2ed', label: 'Borgogna' },
        { bg: '#d6cfc4', fg: '#1a2332', label: 'Pietra' },
        { bg: '#f5f2ed', fg: '#1a2332', label: 'Camicia' },
      ],
      btn2: { bg: '#1a2332', fg: '#f5f2ed' },
      why: 'Navy + cammello + borgogna = il papà che esce dall\'ufficio e sale sul palco.',
    },
    {
      name: 'Gelato al Parco',
      vibe: 'dolce · famiglia · domenica pomeriggio',
      dark: '#3a2e4a', light: '#fef6f0', accent: '#e67e5a',
      swatches: [
        { bg: '#3a2e4a', fg: '#fef6f0', label: 'Prugna' },
        { bg: '#e67e5a', fg: '#fef6f0', label: 'Albicocca' },
        { bg: '#f4c065', fg: '#3a2e4a', label: 'Vaniglia' },
        { bg: '#8bc5a3', fg: '#3a2e4a', label: 'Pistacchio' },
        { bg: '#fef6f0', fg: '#3a2e4a', label: 'Panna' },
      ],
      badgeBg: '#e67e5a',
      btn2: { bg: '#8bc5a3', fg: '#3a2e4a' },
      why: 'Colori da gelato artigianale — dolci ma non infantili.',
    },
    {
      name: 'Arcella Notte',
      vibe: 'urbano · quartiere · radici padovane',
      dark: '#1c1c2e', light: '#f2ede6', accent: '#cf6347',
      swatches: [
        { bg: '#1c1c2e', fg: '#f2ede6', label: 'Asfalto' },
        { bg: '#cf6347', fg: '#f2ede6', label: 'Mattone' },
        { bg: '#4a7c6a', fg: '#f2ede6', label: 'Platano' },
        { bg: '#d4a85c', fg: '#1c1c2e', label: 'Lampione' },
        { bg: '#f2ede6', fg: '#1c1c2e', label: 'Intonaco' },
      ],
      btn2: { bg: '#1c1c2e', fg: '#f2ede6' },
      why: 'Arcella, il quartiere delle sagre e delle prove.',
    },
    {
      name: 'Nol Vien',
      vibe: 'a cappella · 5 voci pure · essenziale',
      dark: '#1e1e28', light: '#f7f5f2', accent: '#c45c4a',
      swatches: [
        { bg: '#1e1e28', fg: '#f7f5f2', label: 'Vuoto' },
        { bg: '#c45c4a', fg: '#f7f5f2', label: 'Voce' },
        { bg: '#3a3a4a', fg: '#f7f5f2', label: 'Eco' },
        { bg: '#d8d0c4', fg: '#1e1e28', label: 'Risonanza' },
        { bg: '#f7f5f2', fg: '#1e1e28', label: 'Silenzio' },
      ],
      btn2: { bg: '#1e1e28', fg: '#f7f5f2' },
      why: 'La palette più essenziale, come un brano a cappella.',
    },
    {
      name: 'Teatro e Sagra',
      vibe: 'ibrido · teatro + piazza · professionisti + famiglie',
      dark: '#2a1f30', light: '#faf6ed', accent: '#c87d3a',
      swatches: [
        { bg: '#2a1f30', fg: '#faf6ed', label: 'Sipario' },
        { bg: '#8a3540', fg: '#faf6ed', label: 'Velluto' },
        { bg: '#c87d3a', fg: '#faf6ed', label: 'Legno' },
        { bg: '#6a9a70', fg: '#faf6ed', label: 'Sagra' },
        { bg: '#faf6ed', fg: '#2a1f30', label: 'Locandina' },
      ],
      btn2: { bg: '#8a3540', fg: '#faf6ed' },
      why: 'Sipario viola, velluto rosso, legno del palco, verde della sagra.',
    },
    {
      name: 'Mai Finti',
      vibe: 'autenticità · genuino · senza filtri',
      dark: '#2c2820', light: '#f5f0e4', accent: '#c07040',
      swatches: [
        { bg: '#2c2820', fg: '#f5f0e4', label: 'Terra' },
        { bg: '#c07040', fg: '#f5f0e4', label: 'Cuoio' },
        { bg: '#7a8a5a', fg: '#f5f0e4', label: 'Oliva' },
        { bg: '#d4b880', fg: '#2c2820', label: 'Grano' },
        { bg: '#f5f0e4', fg: '#2c2820', label: 'Grezzo' },
      ],
      btn2: { bg: '#2c2820', fg: '#f5f0e4' },
      why: 'Colori da materiali veri: terra, cuoio, oliva, grano.',
    },
  ],
};
